apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
spec:
  restartPolicy: Never
  containers:
  - name: iperf-server
    image: dandor22/iperf3 
    args: ["iperf3","-s"]
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5201
    volumeMounts:
    - name: hostpath-volume
      mountPath: /mnt/iperf3
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /mnt/iperf3
      type: DirectoryOrCreate

