#!/bin/bash
for i in {1..4000}; do
    current_time_1=$(python3 -c "import datetime; print(datetime.datetime.now().strftime('%s.%f'))")
    kubectl apply -f timestamp_pod.yaml
    current_time_2=$(python3 -c "import datetime; print(datetime.datetime.now().strftime('%s.%f'))")
    sleep 2
    current_time_3=$(kubectl exec timestamp -- cat /root/result)
    echo "======$i======" >> /home/cloudadmin/k8s_timestamp
    echo "$current_time_1 ; $current_time_2; $current_time_3 ">> /home/cloudadmin/k8s_timestamp
    kubectl delete -f timestamp_pod.yaml
    sleep 2
done
echo "================================================================="
echo "Скрипт отработал!"
echo "================================================================="
