apiVersion: v1
kind: Pod
metadata:
  name: anybench
spec:
  restartPolicy: Never
  runtimeClassName: runc  
  containers:
  - name: anybench
    image: dandor22/anybenchtest:multi2
    command: ["/bin/sh", "-c"]
    args: ["cd /home/test/anybench/src && /home/test/anybench/src/run.sh && cp -r /home/test/anybench/results/amd64 /mnt/anybench/runc/$(date +%s)"]
    volumeMounts:
    - name: hostpath-volume
      mountPath: /mnt/anybench/runc
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /mnt/anybench/runc
      type: DirectoryOrCreate
