apiVersion: v1
kind: Pod
metadata:
  name: timestamp
spec:
  restartPolicy: Never      
  runtimeClassName: kata-qemu
  containers:
  - name: timestamp
    image: ubuntu:20.04
    command: ["/bin/bash", "-c"]
    args: ["date +%s.%N >> /mnt/run_container/run_container_output && sleep 10"]
    volumeMounts:
    - name: hostpath-volume
      mountPath: /mnt/run_container
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /mnt/run_container
      type: DirectoryOrCreate
