FROM alpine:latest

# Устанавливаем Python
RUN apk add --no-cache python3

# Копируем скрипт внутрь контейнера
COPY start.sh /usr/local/bin/start.sh

# Делаем скрипт исполняемым
RUN chmod +x /usr/local/bin/start.sh

# Запускаем скрипт при запуске контейнера
CMD /usr/local/bin/start.sh && sleep infinity
