apiVersion: v1
kind: Pod
metadata:
  name: timestamp
spec:
  restartPolicy: Never
  runtimeClassName: runc
  containers:
  - name: timestamp
    image: ubuntu:20.04
    command: ["/bin/bash", "-c"]
    args: ["date +%s.%N >> /mnt/run_container/runc/run_container_output && sleep 10"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: hostpath-volume
      mountPath: /mnt/run_container/runc
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /mnt/run_container/runc
      type: DirectoryOrCreate
