apiVersion: v1
kind: Pod
metadata:
  name: iperf-client
spec:
  restartPolicy: Never
  containers:
  - name: iperf-client
    image: dandor22/iperf3
    command: ["/bin/sh","-c"]
    args: ["iperf3 -c 192.168.0.1 > /mnt/iperf3/$(date +%T).txt"]
    ports:
    volumeMounts:
    - name: hostpath-volume
      mountPath: /mnt/iperf3
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /mnt/iperf3
      type: DirectoryOrCreate
