apiVersion: v1
kind: Pod
metadata:
  name: timestamp
spec:
  restartPolicy: Never      
  containers:
  - name: timestamp
    image: ubuntu:20.04
    command: ["/bin/bash", "-c"]
    args: ["sleep 3600"]
    volumeMounts:
    - name: hostpath-volume
      mountPath: /mnt/iperf3
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /mnt/iperf3
      type: DirectoryOrCreate
